#!/bin/bash

set -e

# Clean up
rm -rf lib
rm -rf lib-esm

# Compile
npx cross-env BABEL_MODULE=commonjs babel src --out-dir lib --extensions ".js,.ts"
npx babel src --out-dir lib-esm --extensions ".js,.ts"

# Type check
npx tsc

# Copy type declarations
npx copyfiles -u 1 "./dist/**/*.d.ts" ./lib
npx copyfiles -u 1 "./dist/**/*.d.ts" ./lib-esm
