name: Release Candidate
on:
  push:
    branches:
      - 'changeset-release/main'

jobs:
  release-candidate:
    name: npm
    if: ${{ github.repository == 'primer/behaviors' }}
    uses: primer/.github/.github/workflows/release_candidate.yml@v2.0.0
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_AUTH_TOKEN_SHARED }}
